openapi: 3.2.0
info:
  description: REST API for ChartHop
  version: V1.0.0
  title: ChartHop Query API
  contact:
    name: ChartHop
    url: https://www.charthop.com
    email: support@charthop.com
servers:
- url: https://localhost
- url: http://localhost
tags:
- name: Query
paths:
  /v1/org/{orgId}/query:
    get:
      tags:
      - Query
      summary: Get a list of query tokens
      operationId: listQueryTokens
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug
        required: true
        schema:
          type: string
      - name: from
        in: query
        description: Action id to start paginating from
        required: false
        schema:
          type: string
      - name: limit
        in: query
        description: Number of results to return
        required: false
        schema:
          type: integer
          format: int32
      - name: returnAccess
        in: query
        description: 'Return access information -- pass a list of actions to check, for example: create,update,delete'
        required: false
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultsQueryToken'
        '400':
          description: bad request
        '401':
          description: not authorized
        '404':
          description: not found
    post:
      tags:
      - Query
      summary: Create a live query token
      operationId: createQuery
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryToken'
        '400':
          description: bad request
        '401':
          description: not authorized
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateQueryToken'
        required: true
  /v1/org/{orgId}/query/{queryToken}:
    delete:
      tags:
      - Query
      summary: Expire a previously created live query immediately
      operationId: expire
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: queryToken
        in: path
        description: Query token (either id or token string)
        required: true
        schema:
          type: string
      responses:
        '202':
          description: snapshot currently building
        '400':
          description: bad request
        '401':
          description: not authorized
        '404':
          description: not found
    get:
      tags:
      - Query
      summary: Return the results of a previously created live query
      operationId: query
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: queryToken
        in: path
        description: Query token
        required: true
        schema:
          type: string
      - name: format
        in: query
        description: Data format to use; default is json, can also use json-extended or json-readable
        required: false
        schema:
          type: string
      - name: splitColumns
        in: query
        description: Whether to split complex-datatype columns
        required: false
        schema:
          type: boolean
      responses:
        '202':
          description: snapshot currently building
        '400':
          description: bad request
        '401':
          description: not authorized
        '404':
          description: not found
  /v1/org/{orgId}/query/{queryToken}/iqy:
    get:
      tags:
      - Query
      summary: Download an IQY file for a previously created live query
      operationId: downloadIqyFile
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: queryToken
        in: path
        description: Query token
        required: true
        schema:
          type: string
      - name: format
        in: query
        description: Data format to use; default is html-display, can also use html-export
        required: false
        schema:
          type: string
      - name: splitColumns
        in: query
        description: Whether to split complex-datatype columns
        required: false
        schema:
          type: boolean
      responses:
        '202':
          description: snapshot currently building
        '400':
          description: bad request
        '401':
          description: not authorized
        '404':
          description: not found
components:
  schemas:
    ResultsQueryToken:
      type: object
      required:
      - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/QueryToken'
        next:
          type: string
        access:
          type: array
          items:
            $ref: '#/components/schemas/ResultsAccess'
    QueryToken:
      type: object
      required:
      - id
      - token
      - orgId
      - userId
      - type
      - params
      properties:
        id:
          type: string
          description: globally unique id for query token
          example: 588f7ee98f138b19220041a7
        token:
          type: string
          description: globally unique random token string
        orgId:
          type: string
          description: id of org
          example: 588f7ee98f138b19220041a7
        userId:
          type: string
          description: id of user
          example: 588f7ee98f138b19220041a7
        label:
          type: string
          description: query details on data that is being synced
        type:
          type: string
          description: query type
        path:
          type: string
          description: query path (deprecated)
        params:
          type: object
          description: query params
          additionalProperties:
            type: object
        accessCount:
          type: integer
          format: int64
          description: total number of uses
        createAt:
          type: string
          description: created timestamp
          example: '2016-11-16T13:40:47Z'
        expireAt:
          type: string
          description: expire timestamp
          example: '2016-11-16T13:40:47Z'
        activeAt:
          type: string
          description: last active timestamp
          example: '2016-11-16T13:40:47Z'
    CreateQueryToken:
      type: object
      required:
      - type
      - params
      properties:
        type:
          type: string
          description: query type
        params:
          type: object
          description: query params
          additionalProperties:
            type: object
    AccessAction:
      type: object
      required:
      - action
      properties:
        action:
          type: string
        fields:
          type: array
          uniqueItems: true
          items:
            type: string
        types:
          type: array
          uniqueItems: true
          items:
            type: string
    ResultsAccess:
      type: object
      required:
      - allowed
      properties:
        ids:
          type: array
          uniqueItems: true
          items:
            type: string
            example: 588f7ee98f138b19220041a7
        allowed:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/AccessAction'
