openapi: 3.2.0
info:
  description: REST API for ChartHop
  version: V1.0.0
  title: ChartHop Email Template API
  contact:
    name: ChartHop
    url: https://www.charthop.com
    email: support@charthop.com
servers:
- url: https://localhost
- url: http://localhost
tags:
- name: Email Template
paths:
  /v1/email-template:
    post:
      tags:
      - Email Template
      summary: Create a new email template
      operationId: createEmailTemplate
      responses:
        '201':
          description: email template created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailTemplate'
        '400':
          description: invalid data
        '401':
          description: not authorized
        '403':
          description: permission denied
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEmailTemplate'
        description: Email template to create
        required: true
  /v1/email-template/essential:
    get:
      tags:
      - Email Template
      summary: Return all essential email templates
      operationId: getEssentialEmailTemplates
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultsEmailTemplate'
        '400':
          description: bad request
        '404':
          description: not found
  /v1/email-template/name/{name}:
    get:
      tags:
      - Email Template
      summary: Return the email template by name
      operationId: getEmailTemplateByName
      parameters:
      - name: name
        in: path
        description: Email template name
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailTemplate'
        '400':
          description: bad request
        '404':
          description: not found
  /v1/email-template/non-essential:
    get:
      tags:
      - Email Template
      summary: Return all non-essential email templates
      operationId: getNonEssentialEmailTemplates
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultsEmailTemplate'
        '400':
          description: bad request
        '404':
          description: not found
  /v1/email-template/{emailTemplateId}:
    patch:
      tags:
      - Email Template
      summary: Update an existing email template
      operationId: updateEmailTemplate
      parameters:
      - name: emailTemplateId
        in: path
        description: Email template id
        required: true
        schema:
          type: string
      responses:
        '204':
          description: email template updated
        '400':
          description: invalid data
        '401':
          description: not authorized
        '403':
          description: permission denied
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEmailTemplate'
        description: Email template data to update
        required: true
components:
  schemas:
    EmailTemplate:
      type: object
      required:
      - id
      - name
      - category
      properties:
        id:
          type: string
          description: globally unique id
          example: 588f7ee98f138b19220041a7
        name:
          type: string
          description: name of the email template
          example: self_serve_welcome
        category:
          type: string
          description: email category
          enum:
          - ADMINISTRATIVE
          - BILLING
          - DATA_IMPORT_AND_SYNC_STATUS
          - TRIAL_REMINDERS
          - APPROVAL_NOTIFICATIONS
    ResultsEmailTemplate:
      type: object
      required:
      - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/EmailTemplate'
        next:
          type: string
        access:
          type: array
          items:
            $ref: '#/components/schemas/ResultsAccess'
    UpdateEmailTemplate:
      type: object
      properties:
        name:
          type: string
          description: name of the email template
          example: self_serve_welcome
        category:
          type: string
          description: email category
          enum:
          - ADMINISTRATIVE
          - BILLING
          - DATA_IMPORT_AND_SYNC_STATUS
          - TRIAL_REMINDERS
          - APPROVAL_NOTIFICATIONS
    CreateEmailTemplate:
      type: object
      required:
      - name
      - category
      properties:
        name:
          type: string
          description: name of the email template
          example: self_serve_welcome
        category:
          type: string
          description: email category
          enum:
          - ADMINISTRATIVE
          - BILLING
          - DATA_IMPORT_AND_SYNC_STATUS
          - TRIAL_REMINDERS
          - APPROVAL_NOTIFICATIONS
    AccessAction:
      type: object
      required:
      - action
      properties:
        action:
          type: string
        fields:
          type: array
          uniqueItems: true
          items:
            type: string
        types:
          type: array
          uniqueItems: true
          items:
            type: string
    ResultsAccess:
      type: object
      required:
      - allowed
      properties:
        ids:
          type: array
          uniqueItems: true
          items:
            type: string
            example: 588f7ee98f138b19220041a7
        allowed:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/AccessAction'
