openapi: 3.2.0
info:
  description: REST API for ChartHop
  version: V1.0.0
  title: ChartHop Status API
  contact:
    name: ChartHop
    url: https://www.charthop.com
    email: support@charthop.com
servers:
- url: https://localhost
- url: http://localhost
tags:
- name: Status
paths:
  /v1/status:
    get:
      tags:
      - Status
      summary: Returns true if the API is up and available
      operationId: isOk
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OkResponse'
components:
  schemas:
    OkResponse:
      type: object
      required:
      - ok
      properties:
        ok:
          type: boolean
          description: whether the status is okay
          example: 'true'
