openapi: 3.2.0
info:
  description: REST API for ChartHop
  version: V1.0.0
  title: ChartHop Exchange Rate API
  contact:
    name: ChartHop
    url: https://www.charthop.com
    email: support@charthop.com
servers:
- url: https://localhost
- url: http://localhost
tags:
- name: Exchange Rate
paths:
  /v1/org/{orgId}/exchange-rate/{date}:
    get:
      tags:
      - Exchange Rate
      summary: Return the exchange rates on a particular date
      operationId: getExchangeRates
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: date
        in: path
        description: Date to use
        required: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRate'
        '400':
          description: bad request
        '401':
          description: not authorized
        '404':
          description: not found
    patch:
      tags:
      - Exchange Rate
      summary: Update the USD-based exchange rates for a particular date.
      operationId: setExchangeRates
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: date
        in: path
        description: Date to use
        required: true
        schema:
          type: string
          format: date
      responses:
        '400':
          description: bad request
        '401':
          description: not authorized
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateExchangeRate'
        required: true
    delete:
      tags:
      - Exchange Rate
      summary: Delete a custom exchange rate on a particular date
      operationId: deleteExchangeRate
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: date
        in: path
        description: Date to use
        required: true
        schema:
          type: string
          format: date
      - name: currencyCode
        in: query
        description: Currency code
        required: true
        schema:
          type: string
      responses:
        '400':
          description: bad request
        '401':
          description: not authorized
        '404':
          description: not found
  /v1/org/{orgId}/exchange-rate/{date}/custom:
    get:
      tags:
      - Exchange Rate
      summary: Return org custom exchange rates
      operationId: getCustomExchangeRates
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: date
        in: path
        description: Date to use
        required: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRate'
        '400':
          description: bad request
        '401':
          description: not authorized
        '404':
          description: not found
  /v1/org/{orgId}/exchange-rate/{date}/custom/bulkupdate:
    post:
      tags:
      - Exchange Rate
      summary: Bulk update custom currency rates in org custom exchange rates
      operationId: bulkUpdateCustomExchangeRates
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: date
        in: path
        description: Date to use
        required: true
        schema:
          type: string
          format: date
      - name: addRates
        in: query
        description: Boolean to determine whether to add or remove rates from update
        required: false
        schema:
          type: boolean
      responses:
        '400':
          description: bad request
        '401':
          description: not authorized
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpdateExchangeRate'
        description: Update data
        required: true
  /v1/org/{orgId}/exchange-rate/{date}/global:
    get:
      tags:
      - Exchange Rate
      summary: Return the global exchange rates based on USD for a particular date
      operationId: getGlobalExchangeRates
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: date
        in: path
        description: Date to use
        required: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRate'
        '400':
          description: bad request
        '401':
          description: not authorized
        '404':
          description: not found
  /v1/org/{orgId}/exchange-rate/{date}/history:
    get:
      tags:
      - Exchange Rate
      summary: Return org custom exchange rates
      operationId: getCurrencyRateHistory
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: date
        in: path
        description: Date to use
        required: true
        schema:
          type: string
          format: date
      - name: currency
        in: query
        description: Currency to search for
        required: true
        schema:
          type: string
      - name: fromDate
        in: query
        description: Start date for search
        required: true
        schema:
          type: string
          format: date
      - name: toDate
        in: query
        description: End date for search
        required: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExchangeRate'
        '400':
          description: bad request
        '401':
          description: not authorized
        '404':
          description: not found
components:
  schemas:
    ExchangeRate:
      type: object
      required:
      - id
      - date
      - currency
      - rates
      properties:
        id:
          type: string
          description: globally unique id
          example: 588f7ee98f138b19220041a7
        orgId:
          type: string
          description: org id, if an org-specific exchange rate is in use
          example: 588f7ee98f138b19220041a7
        date:
          type: string
          format: date
          description: date
        currency:
          type: string
          description: base currency
        rates:
          type: object
          description: exchange rates, per currency - the multiplier to convert the base currency into the foreign currency
          additionalProperties:
            type: number
        updateAt:
          type: string
          description: updated timestamp
          example: '2017-01-24T13:57:52Z'
    UpdateExchangeRate:
      type: object
      properties:
        date:
          type: string
          format: date
          description: date
        rates:
          type: object
          description: exchange rates, per currency - the multiplier to convert the base currency into the foreign currency
          additionalProperties:
            type: number
