openapi: 3.2.0
info:
  description: REST API for ChartHop
  version: V1.0.0
  title: ChartHop Saml API
  contact:
    name: ChartHop
    url: https://www.charthop.com
    email: support@charthop.com
servers:
- url: https://localhost
- url: http://localhost
tags:
- name: SAML
paths:
  /saml/org/{orgId}/xml-cert:
    post:
      tags:
      - SAML
      summary: Save per org Xml Cert from IDP
      operationId: uploadXmlCertificate
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: idp
        in: query
        description: Identifier Provider
        required: true
        schema:
          type: string
      responses:
        '400':
          description: invalid data
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
    get:
      tags:
      - SAML
      summary: Save per org Xml Cert from IDP
      operationId: getXmlCertificate
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: idp
        in: query
        description: Identifier Provider
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: string
        '400':
          description: invalid data
  /saml/sso/{org}:
    post:
      tags:
      - SAML
      summary: Single sign on URL, where SAML assertion is perform
      operationId: sso
      parameters:
      - name: prevToken
        in: cookie
        required: false
        schema:
          type: string
      - name: org
        in: path
        description: Org slug
        required: true
        schema:
          type: string
      responses:
        '400':
          description: invalid data
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                SAMLResponse:
                  type: string
                  description: SAML Response
                RelayState:
                  type: string
                  description: Relay State
              required:
              - SAMLResponse
  /saml/{org}/login:
    post:
      tags:
      - SAML
      summary: Return an redirect to the designated Idp, given an identity provider
      operationId: redirectToIdp
      parameters:
      - name: org
        in: path
        description: Org slug
        required: true
        schema:
          type: string
      - name: idp
        in: query
        description: Identifier Provider
        required: false
        schema:
          type: string
      - name: clientId
        in: query
        description: clientId
        required: false
        schema:
          type: string
      - name: codeChallenge
        in: query
        description: codeChallenge
        required: false
        schema:
          type: string
      - name: codeChallengeMethod
        in: query
        description: codeChallengeMethod
        required: false
        schema:
          type: string
      - name: redirectUri
        in: query
        description: redirectUri
        required: false
        schema:
          type: string
      responses:
        '400':
          description: invalid data
