openapi: 3.2.0
info:
  description: REST API for ChartHop
  version: V1.0.0
  title: ChartHop Access API
  contact:
    name: ChartHop
    url: https://www.charthop.com
    email: support@charthop.com
servers:
- url: https://localhost
- url: http://localhost
tags:
- name: Access
paths:
  /v1/org/{orgId}/access/entity/{type}:
    get:
      tags:
      - Access
      summary: Return the appropriate actions that can be performed on an entity or set of…
      operationId: getEntityAccess
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: type
        in: path
        description: Entity type
        required: true
        schema:
          type: string
      - name: id
        in: query
        description: Entity ids
        required: false
        schema:
          type: string
      - name: action
        in: query
        description: Actions, defaults to update,delete
        required: false
        schema:
          type: string
      - name: fields
        in: query
        description: Fields to check, defaults to all fields
        required: false
        schema:
          type: string
      - name: date
        in: query
        description: Date, defaults to today
        required: false
        schema:
          type: string
          format: date
      - name: scenarioId
        in: query
        description: Scenario id, defaults to primary
        required: false
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessResponse'
        '401':
          description: unauthorized
        '404':
          description: not found
  /v1/org/{orgId}/access/ui:
    get:
      tags:
      - Access
      summary: Return the appropriate actions that can be performed on the ui
      operationId: getUiAccess
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                uniqueItems: true
                items:
                  type: string
        '401':
          description: unauthorized
        '404':
          description: not found
components:
  schemas:
    AccessAction:
      type: object
      required:
      - action
      properties:
        action:
          type: string
        fields:
          type: array
          uniqueItems: true
          items:
            type: string
        types:
          type: array
          uniqueItems: true
          items:
            type: string
    ResultsAccess:
      type: object
      required:
      - allowed
      properties:
        ids:
          type: array
          uniqueItems: true
          items:
            type: string
            example: 588f7ee98f138b19220041a7
        allowed:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/AccessAction'
    AccessResponse:
      type: object
      properties:
        access:
          type: array
          items:
            $ref: '#/components/schemas/ResultsAccess'
