swagger: '2.0'
info:
  description: REST API for ChartHop
  version: V1.0.0
  title: ChartHop access usage API
  contact:
    name: ChartHop
    url: https://www.charthop.com
    email: support@charthop.com
host: localhost
schemes:
- https
- http
consumes:
- application/json
produces:
- application/json
tags:
- name: usage
paths:
  /v1/org/{orgId}/usage/upgrade:
    post:
      tags:
      - usage
      summary: Signal interest in upgrading to a paid plan
      operationId: recordUpgradeInterest
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        type: string
      - name: module
        in: query
        description: Module name
        required: false
        type: string
      responses:
        '401':
          description: unauthorized
  /v1/org/{orgId}/usage/{type}:
    post:
      tags:
      - usage
      summary: Record usage of a product feature
      operationId: recordUsage
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        type: string
      - name: type
        in: path
        description: Type of usage
        required: true
        type: string
      - name: entityId
        in: query
        description: Entity id, if applicable
        required: false
        type: string
      responses:
        '401':
          description: unauthorized
