openapi: 3.2.0
info:
  description: REST API for ChartHop
  version: V1.0.0
  title: ChartHop Usage API
  contact:
    name: ChartHop
    url: https://www.charthop.com
    email: support@charthop.com
servers:
- url: https://localhost
- url: http://localhost
tags:
- name: Usage
paths:
  /v1/org/{orgId}/usage/upgrade:
    post:
      tags:
      - Usage
      summary: Signal interest in upgrading to a paid plan
      operationId: recordUpgradeInterest
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: module
        in: query
        description: Module name
        required: false
        schema:
          type: string
      responses:
        '401':
          description: unauthorized
  /v1/org/{orgId}/usage/{type}:
    post:
      tags:
      - Usage
      summary: Record usage of a product feature
      operationId: recordUsage
      parameters:
      - name: orgId
        in: path
        description: Org identifier (either id or slug)
        required: true
        schema:
          type: string
      - name: type
        in: path
        description: Type of usage
        required: true
        schema:
          type: string
      - name: entityId
        in: query
        description: Entity id, if applicable
        required: false
        schema:
          type: string
      responses:
        '401':
          description: unauthorized
